server:
  port: 9290
spring:
  application:
    name: config-server
  profiles:
    active: git, dev
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/
        git:
          uri: https://github.com/SuanCaiYv/config-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://${base.host}:${base.port}/eureka/
    healthcheck:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: dev
base:
  host: 127.0.0.1
  port: 9190
---
spring:
  config:
    activate:
      on-profile: prod
base:
  host: 81.68.154.171
  port: 9190
